service: GlobetrotterAPI

frameworkVersion: 2

provider: 
  name: aws
  region: us-east-1
  runtime: nodejs14.x

functions:
  app:
    handler: src/app.handler
    events: 
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true


 
