service: GlobetrotterAPI

frameworkVersion: '3'

provider: 
  name: aws
  region: us-east-1
  runtime: nodejs14.x
  environment:
    AWS_ACCESS_KEY_ID: AKIAZYS6U4Y5IHYDJXHR
    AWS_SECRET_ACCESS_KEY: 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
    TABLE_NAME:
      Ref: Race


functions:
  app:
    handler: build/app.handler
    events: 
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

resources:
  Resources:
    RaceTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Race
        AttributeDefinitions:
          - AttributeName: RaceID
            AttributeType: S
        KeySchema:
          - AttributeName: RaceID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1



 
