service: GlobetrotterAPI

frameworkVersion: '3'

provider: 
  name: aws
  region: us-east-1
  runtime: nodejs14.x
  environment:
    GOOGLE_MAPS_API_KEY: ${ssm:google_api_key}
    TABLE_NAME:
      Ref: RaceTable


functions:
  app:
    handler: build/app.handler
    events: 
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

resources:
  Resources:
    RaceTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Race
        AttributeDefinitions:
          - AttributeName: RaceID
            AttributeType: S
        KeySchema:
          - AttributeName: RaceID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1



 
