name: deploy zip to lambda
on: [push]
jobs:

  deploy_zip:
    name: deploy lambda function
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.13.x]
    steps:
      - name: checkout source code
        uses: actions/checkout@v2
      - name: zip files
        uses: papeloto/action-zip@v1
        with:
          files: ./
          dest: GlobeTrotterAPI.zip
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{secrets.ACCESS_KEY_ID}}
          aws_secret_access_key: ${{secrets.ACCESS_KEY_KEY }}
          aws_region: us-west-1
          function_name: GlobeTrotterLambda
          zip_file: GlobeTrotterAPI.zip
